### PR TITLE
add: Thailand Fansub - Spring 2017

### PR DESCRIPTION
**Pull request by pureexe**
#Add Thai fansub on Spring 2017

Note:
- Some anime that don't exist on Myanimelist.net will use images from livechart.net instead.
- Conan The Movie 21 only simulcast on application [AIS Play](http://ais.co.th/playapp) (Android/IOS) So, it doesn't have url link.

Best Regard
- Pakkapon

### CODE REVIEW

**Comment by FansubDB** [comment]
@pureexe thank you for the PR

Can you delete all URL link of simulcast? In the case of putting URL, I would put canonical URL (so instead of `"url": "http://www.majorcineplex.com/movie/fairy-tail-movie-2-dragon-cry"`, put `"url": "http://www.majorcineplex.com/"`), and like I said in #62 it seems for me like an hidden ad.

What do you think?

**Comment by pureexe** [comment]
@FansubDB  about simulcast.
Sometimes anime licensor in Thailand use 3rd-party service for simulcast, but Sometimes they simulcast on there website. for simulcast data I used name as name of Licensor. but about URL simulcast. I add their simulcast link.

So you will See `Fairy Tail Movie 2: dragon cry` have licensed in Thailand by DEX but simulcast by MajorCliniplex. Should I change Url to dexchannel.com (Dex's simulcast website) or still use  majorcineplex.com ?

**Comment by FansubDB** [comment]
@pureexe so for me, simulcast is MajorCliniplex.

For the time, my idea is to not put link for simulcast

**Comment by pureexe** [comment]
1871924
- remove all simulcast link
- and change licensor name to streaming service name (For Gin no Guardian and Sakurada Reset Dex use own website to simulcast)

**Pull request merged**
