### PR TITLE
Go to the API | Update Anime "image" URL for less typing.

### PR DESCRIPTION
**Pull request by KasaiDot**
A small PR for converting a bit more FansubDB static to the dynamic one with MAL/HummingBird API (though they'r quite ugly)

No need to accept this one now, just see what i want to change & try to convert the site to the API.
If i'm right in the image url they'r the "anime_id" so with a bit requests with HummingBird API (since it's the one who doesn't need to be authenticated, we can get the "mal_id" and _maybe_ request the image url without to do anything.

[HB API](https://github.com/hummingbird-me/hummingbird/wiki/API-Reference) (use the v1)

Referenced to the #48 & #50

### CODE REVIEW

**Comment by FansubDB** [comment]
I'm waiting HB API v3, we can't use HB API v1 because it doesn't accept CORS (mandatory for javascript) (and v2 is with authentification 😞 )

**Comment by KasaiDot** [comment]
Oh i didn't know they don't implement it.
Otherwise we can "create" a one with js and for the image we get them from MAL, no?

**Comment by FansubDB** [comment]
You need credentials for using MAL API.

**Comment by KasaiDot** [comment]
yeah, but for "get" the image no need, no, i mean we can do request on the web page like "https://myanimelist.net/anime/31404/Netoge_no_Yome_wa_Onnanoko_ja_Nai_to_Omotta" and get the image from this?

**Comment by FansubDB** [comment]
I don't know if I should developp this. The branch [v3 I want to create](https://github.com/FansubDB/fansubdb.github.io/tree/FansubDB-v3.0) with Hummingbird API will have this kind of feature. The anime object will only contains `hummingbird_id`, and this id will be used to show a picture and other detail, I hope.

**Comment by KasaiDot** [comment]
Okay, no problem.

**Comment by FansubDB** [comment]
Oh, and for "less typing", I just copy/paste the image URL, I don't rewrite it 😆

**Comment by FansubDB** [comment]
> we can do request on the web page like "https://myanimelist.net/anime/31404/Netoge_no_Yome_wa_Onnanoko_ja_Nai_to_Omotta" and get the image from this?

I only use HTML/JS/CSS, so you can't parse web pages if there is no CORS (MAL website has not CORS-enable).<br>JS is very restrictive: only picture or other content using CORS-enable thing.

**Pull request closed without merging**
