### PR TITLE
Thai: update fansubber url for winter 2016

### PR DESCRIPTION
**Pull request by pureexe**
I just add fansubber's Facebook fanpage.

In Thailand, all fansubber always shared their files to fan page.

And add anime link for simulcast [Daisuki.net](https://www.daisuki.net/th/th) [DexChannel](http://dexchannel.com) and [Majorcineplex](http://www.majorcineplex.com).

### CODE REVIEW

**Comment by FansubDB** [comment]
@pureexe are they ok for sharing their link?
Normally I ask if you have asked to the owner of the website if they are ok to put their website on this FansubDB.

**Comment by pureexe** [comment]
I have not asked them yet.
I will ask them for permission first.

**Comment by FansubDB** [comment]
thank you

**Comment by FansubDB** [comment]
@pureexe any news?

**Comment by pureexe** [comment]
Some fansubber ignore my message and isn't reply.
Maybe i should cancel this pull request.

**Comment by FansubDB** [comment]
@pureexe you can always put the fansubber who respond "yes" to you

**Pull request closed without merging**
