### PR TITLE
Add one JSON File per id

### PR DESCRIPTION
**Pull request by FansubDB**
* 1 id from hummingbird_id
 * hummingbird because open API and [this](https://github.com/FansubDB/fansubdb.github.io/tree/hummingbird-API)

### CODE REVIEW

**Comment by FansubDB** [comment]
New data struct:

* winter.json

```
{
	"name": "name",
	"group": "group",
	"message": "",
	"lbl_tv": "TV",
	"lbl_ova": "OVA",
	"lbl_movie": "Movies",
	"tv": [{
		"name": "Active Raid: Kidou Kyoushuushitsu Dai-Hakkei",
		"hummingbird_id": "11456",
		"json": "11456.json",
		"leftover": "true",
	}]
}
```

* a new file; in our case ```11456.json``` locate in /:lang/:type (type is ```tv```/```movie```/```ova```)

```
{
	"name": "Active Raid: Kidou Kyoushuushitsu Dai-Hakkei",
	"image": "http://cdn.myanimelist.net/images/anime/9/76669.jpg",
  "hummingbird_id": "11456",
	"group": [{
		"status": "simulcast",
		"detail": [{
			"name": "Crunchyroll"
		}]
	}]
}
```

**Comment by FansubDB** [comment]
@KasaiDot can you test it?

1. Just download the [zip of the PR](https://github.com/FansubDB/fansubdb.github.io/archive/FansubDB-leftovers.zip) and extract it on a PHP folder
1. Change for example ```fr/2015/hiver.json``` by the first point above
1. Create a file: ```fr/tv/11456.json``` and put the second point above
1. load it on http://IP:PORT/fansubdb.github.io-master/fr/2015/hiver.html and see it!<br> Because ```"leftover": "true"```, color must be in purple.

**Comment by KasaiDot** [comment]
okay, test it right now.

**Comment by KasaiDot** [comment]
1° : "external/bootstrap.min.css" : add "https:" before "//" for compatibility with Linux "drag & drop"

**Comment by KasaiDot** [comment]
Okay, don't work for me.
the file display nothing.
like the json's file was dead.

11456.json :
``json
{
    "name": "Active Raid: Kidou Kyoushuushitsu Dai-Hakkei",
    "image": "http://cdn.myanimelist.net/images/anime/9/76669.jpg",
  "hummingbird_id": "11456",
    "group": [{
        "status": "simulcast",
        "detail": [{
            "name": "Crunchyroll"
        }]
    }]
}
``

hiver.json
``json
{
    "name": "name",
    "group": "group",
    "message": "",
    "lbl_tv": "TV",
    "lbl_ova": "OVA",
    "lbl_movie": "Movies",
    "tv": [{
        "name": "Active Raid: Kidou Kyoushuushitsu Dai-Hakkei",
        "hummingbird_id": "11456",
        "json": "11456.json",
        "leftover": "true",
    }]
}
``

**Comment by FansubDB** [comment]
You can't drag'n'drop this project. You must to use a php server because:
 * ```Cross origin requests are only supported for protocol schemes```, so the json file can't load
 * and because of bootstap, yes. But because the first point, I won't change "https:" before "//" for compatibility with Linux "drag & drop"

**Comment by FansubDB** [comment]
Here a zip version. But like I said, launch it with a php server.
[fansubdb.github.io-leftover.zip](https://github.com/FansubDB/fansubdb.github.io/files/107957/fansubdb.github.io-leftover.zip)

**Comment by KasaiDot** [comment]
Will try with the new version, report it this night.

**Comment by KasaiDot** [comment]
Okay, test finished.
but they are one "bug".

1° the color diplaying was ok (purple), i see it. (http://i.imgur.com/y5Xk2rj.png)
2° when you change "TV" by "Films" and re-change to "TV" the color won't diplay (http://i.imgur.com/8vl38te.png)

**Comment by KasaiDot** [comment]
Okay, i just found the bug

in the first load the json's files was loaded by the Gist from GitHub.
but for the second it's from the local.

Images : http://i.imgur.com/XN0Kk07.png & http://i.imgur.com/JkKcaGK.png

**Comment by KasaiDot** [comment]
So your update works fine with me.
You can publish it.

**Comment by FansubDB** [comment]
Not sure, but:

* it can be a Chrome issue
* it's because it's loaded from cache (so it's normal?)

**Comment by KasaiDot** [comment]
dunno, did you want to check it?

**Comment by FansubDB** [comment]
I can't reproduce this on my side with Firefox

**Comment by KasaiDot** [comment]
so, i'll try with my side with FF 42.0 in Xubuntu 15.0
tell you the results this night or maybe tomorow.

**Comment by KasaiDot** [comment]
For the moment FF seems support it (http://i.imgur.com/S81Vd9M.png)

**Comment by KasaiDot** [comment]
but like Chrome too it's beug when we change the "button" (http://i.imgur.com/lTGEDPb.png)

**Comment by KasaiDot** [comment]
They are really a fck bug when we change (http://i.imgur.com/6mi9Uap.png)
Like Chrome too, the file load from gist in first and from local in second.

**Comment by KasaiDot** [comment]
Okay, found where it bug from me (http://i.imgur.com/6NXXulZ.png) just correct the wrong path, and it's good.

**Comment by KasaiDot** [comment]
testing the corrected version right now.

**Comment by FansubDB** [comment]
Oh, it's when you click on one of the three button?

It's normal, they don't load the gist. I just change one URL, not all (you must to change [here](https://github.com/FansubDB/fansubdb.github.io/blob/FansubDB-leftovers/fr/2015/printemps.html#L45). So it's only a bug for your special drag'n'drop version, not for the GitHub version ^^
Thanks

**Comment by KasaiDot** [comment]
Okay, now it's works perfectly fine for me.
Just correct the things below:

1° (fansubdb.github.io-leftover/fr/2015/hiver.html)
Change 
```html
<script type='text/javascript'>
	readJsonFile('https://gist.githubusercontent.com/FansubDB/e529c7e9a8721e1c92d1/raw/b71ea2403ff80d02b34f3c8fca22a78ccf5a8e15/hiver.json', SEASON, 0);
</script>
```
by
```html
<script type="text/javascript">
	readJsonFile("hiver.json",SEASON,0);
</script>
```

2° (fansubdb.github.io-leftover/fr/2015/hiver.json)
Change
```json
"json": "11456.json",
```
by
```json
"json": "../tv/11456.json",
```

**Comment by FansubDB** [comment]
> 2° (fansubdb.github.io-leftover/fr/2015/hiver.json)
> Change `"json": "11456.json"`, by `"json": "../tv/11456.json"`

why ? The `../tv` are automatically put with my script (`readSerieFile('../' + url + '/' + array[i].json);`)

**Comment by KasaiDot** [comment]
The "../TV" was for the exemple witch i tested on m'y laptop.
--
Envoyé depuis Android mardi, 23 février 2016, 00:54PM +0100 de FansubDB < notifications@github.com> :

**Comment by FansubDB** [comment]
ok :)

**Pull request closed without merging**
